# Generated by Django 3.1.10 on 2023-01-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0005_auto_20200218_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='proof',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
